### ISSUE TITLE
Testnet Chainspec generator endpoint + UI

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/testnet-manager#11]
Creating testnet chainspecs manually is an error prone process.  It can cause hours of frustrations if you launch the testnet with an incorrect chainspec. So IT would be very helpful to have utilities to help with this process such as a form page in the testnet-manager.

Ideally this would let you craft a chainspec file link such as: `http://testnet-manager/api/chainspec?content=base64encodedMap
The base64 encoded map would contains the chainspec details to be inserted into a non-raw JSON chainspec file.

See eg. [zombienet chainspec generation utils](https://github.com/paritytech/zombienet/blob/53e42e8cb2121909d3244ce9518c97b861c7f348/src/chain-spec.ts)

**Comment by BulatSaif** [comment]
My vision how it can be achieved:
### Input data
- base chainspec ( docker image + chain name or json)
- override parameters (bootnodes, keys. ..)
### Output data 
- url with chainspec. 

### Steps
1. Input yaml
```yaml
chainspecs:
  versi: 
    base: {}  
    override: {} # jinja template 
    templates: {} # predefined templates to generate part of  chainspec. 
```
2.  Get base chainspec: 
  a. run docker image with provided  command. 
  b. Verify that output is valid json.
4. Render override json. 
5. Merge base + override json
6. convert to raw chainspec. 
7. publish chainspec

# Example  of input data.
```yaml
chainspecs:
  versi:
    replicas: 8
    base:
      image: paritypr/polkadot-debug:5635-b2cb08a1
      command: build-spec --chain versi-staging
    override:
      name: "Versi",
      id: "versi_v1_10",
      bootNodes: "{{ get_bootNodes }}"
      genesis:
        runtime:
          runtime_genesis_config:
            balances:
              balances: "{{ [[\"5D...xs\", 1000000000000000000]] +  get_balances }}"
            session: "{{ get_session }}"
    templates:
      # returns list of bootnodes. nodekey is taken from vault.
      # [bootnode1, bootnode2]
      get_bootNodes:
        template: "/dns/versi-bootnode-{{ index }}.parity-versi.parity.io/tcp/30333/p2p/{{ key }}"
        nodeKey:
          name: nodekey
          vaultPath: "kv/applications/parity-versi/versi-bootnodes"
          vaultKey: "versi_bootnode_nodekey"
          vaultKeyAppendPodIndex: true
      # returns list of stash accounts with balance.
      # [[account1, balance1], [account2, balance2],...  ]
      get_balances:
        keys:
          - name: gran
            vaultPath: "kv/applications/parity-versi/versi-bootnodes"
            vaultKey: versi_bootnodes_seed
            type: stash
            scheme: sr25519
            # ${HOSTNAME##*-} will be evaluated as the pod index
            extraDerivation: "//versi-bootnode-${HOSTNAME##*-}//stash"
      # returns list of sessions keys.
      # "keys": [
      #  [
      #    "5DV3X8jaZ2pwUFnApusxSQc3hPZrbCKByvdGfLvwFqcKXRte",
      #    "5DV3X8jaZ2pwUFnApusxSQc3hPZrbCKByvdGfLvwFqcKXRte",
      #    {
      #      "grandpa": "5GL8faNkBoJS6TeZANDGjo8PcPyPs5WZQ85J5uB4jqPpyvh8",
      #      "babe": "5FNF9A2TFd8PgutZd8bdPpbR1WSZCcjtnggd9EEq3oVKVM36",
      #      "im_online": "5EycsfQxcsFBjJ6setX8yivnceNiBoZtiQkcryvNQA9K4ULK",
      #      "para_validator": "5DjqDw5NMmFdiafR9oVKZLasjY96jsd4sM5sdhMi8CT29vKx",
      #      "para_assignment": "5F7Ka1qtTNVLityecYunrePHew3xCzV8HwZcrGZ9fuCS9NWv",
      #      "authority_discovery": "5Hb3UnjMkuTWN47mKFxFfrad3gG8QzVNHogq3Nmj9drmnQPZ",
      #      "beefy": "KW7vQVy7rsgoBKjBMSsroY7otKAjSesjexLcQjGFKisbHZT73"
      #    }
      #  ],
      # ...
      # ]
      get_session:
        keys:
          - name: gran
            vaultPath: "kv/applications/parity-versi/versi-bootnodes"
            vaultKey: versi_bootnodes_seed
            type: gran
            scheme: ed25519
            # ${HOSTNAME##*-} will be evaluated as the pod index
            extraDerivation: "//versi-bootnode-${HOSTNAME##*-}//grandpa"
          - name: babe
            vaultPath: "kv/applications/parity-versi/versi-bootnodes"
            vaultKey: versi_bootnodes_seed
            type: babe
            scheme: sr25519
            extraDerivation: "//versi-bootnode-${HOSTNAME##*-}//babe"
          - name: imon
            vaultPath: "kv/applications/parity-versi/versi-bootnodes"
            vaultKey: versi_bootnodes_seed
            type: imon
            scheme: sr25519
            extraDerivation: "//versi-bootnode-${HOSTNAME##*-}//im_online"
          - name: para
            vaultPath: "kv/applications/parity-versi/versi-bootnodes"
            vaultKey: versi_bootnodes_seed
            type: para
            scheme: sr25519
            extraDerivation: "//versi-bootnode-${HOSTNAME##*-}//para_validator"
          - name: asgn
            vaultPath: "kv/applications/parity-versi/versi-bootnodes"
            vaultKey: versi_bootnodes_seed
            type: asgn
            scheme: sr25519
            extraDerivation: "//versi-bootnode-${HOSTNAME##*-}//para_assignment"
          - name: audi
            vaultPath: "kv/applications/parity-versi/versi-bootnodes"
            vaultKey: versi_bootnodes_seed
            type: audi
            scheme: sr25519
            extraDerivation: "//versi-bootnode-${HOSTNAME##*-}//authority_discovery"
```
